site_name: Adèkora Docs
site_url: https://example.com/
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: 'index.md'
  - Phonology:
    - 'Main Page': 'phonology/main.md'
    - 'Consonants': 'phonology/consonants.md'
    - 'Vowels': 'phonology/vowels.md'
    - 'Phonotactics': 'phonology/phonotactics.md'
    - 'Allophony': 'phonology/allophony.md'
    - 'Intonation': 'phonology/intonation.md'
  - 'Writing System':
    - 'Main Page': 'writing/main.md'
    - 'Letters': 'writing/letters.md'
    - 'Numbering': 'writing/numbering.md'
    - 'Punctuation': 'writing/punctuation.md'
    - 'Localizers': 'writing/localizers.md'
    - 'Font': 'writing/font.md'
  - Grammar:
    - 'Main Page': 'grammar/main.md'
    - 'Nouns': 'grammar/nouns.md'
    - 'Verbs': 'grammar/verbs.md'
  - Vocabulary:
    - 'Main Page': 'vocabulary/main.md'
  - Resources:
    - 'IPA Chart': 'resources/ipa_chart.md'
    - 'Mkdocs test page': 'resources/test.md'
markdown_extensions:
  - toc:
      permalink: True
      baselevel: 1
      separator: '-'